server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/one
    username: postgres
    password: rag0bajY
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update